import type { Player } from '../../models/player.model';

export const secretPlayerData: Player[] = [
    {
        position: 'Pixies',
        id: 1000,
        cost: 30,
        playerStats: [7, 1, 3, 6, 7],
        skills: [81, 78, 4, 85],
        primary: ['A'],
        secondary: ['G'],
    },
    {
        position: 'Woad Beserker',
        id: 1001,
        cost: 80,
        playerStats: [5, 4, 5, 6, 8],
        skills: [17, 60],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Fen Guard',
        id: 1002,
        cost: 90,
        playerStats: [5, 4, 5, 5, 9],
        skills: [58, 60],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Fen Beast',
        id: 1003,
        cost: 120,
        playerStats: [4, 5, 6, 6, 10],
        skills: [711, 66, 55, 60, 86, 77],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Treeman',
        id: 1004,
        cost: 120,
        playerStats: [2, 6, 5, 5, 11],
        skills: [71, 55, 58, 59, 84, 60, 86],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Bedouin',
        id: 1005,
        cost: 40,
        playerStats: [6, 3, 3, 4, 8],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Bedouin Throwers',
        id: 1006,
        cost: 70,
        playerStats: [6, 3, 3, 2, 8],
        skills: [22, 46],
        primary: ['G', 'P'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Eunuchs',
        id: 1007,
        cost: 80,
        playerStats: [5, 4, 4, 5, 9],
        skills: [],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Dervishes',
        id: 1008,
        cost: 95,
        playerStats: [7, 3, 3, 5, 9],
        skills: [9, 17],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Sheikh',
        id: 1009,
        cost: 100,
        playerStats: [7, 3, 2, 4, 8],
        skills: [43],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Linewomen',
        id: 1010,
        cost: 70,
        playerStats: [6, 3, 2, 4, 9],
        skills: [],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Sisters',
        id: 1011,
        cost: 100,
        playerStats: [7, 3, 2, 2, 8],
        skills: [46, 1],
        primary: ['G', 'A', 'P'],
        secondary: ['S'],
    },
    {
        position: 'Handmaidens',
        id: 1012,
        cost: 120,
        playerStats: [8, 3, 2, 5, 9],
        skills: [13, 58],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Gor',
        id: 1013,
        cost: 60,
        playerStats: [6, 3, 3, 4, 9],
        skills: [30],
        primary: ['G', 'S'],
        secondary: ['A', 'P', 'M'],
    },
    {
        position: 'Ungor',
        id: 1014,
        cost: 50,
        playerStats: [7, 2, 3, 3, 8],
        skills: [4],
        primary: ['G', 'A'],
        secondary: ['S', 'P', 'M'],
    },
    {
        position: 'Bestigor',
        id: 1015,
        cost: 110,
        playerStats: [6, 4, 3, 5, 9],
        skills: [30],
        primary: ['G', 'S'],
        secondary: ['A', 'M'],
    },
    {
        position: 'Bullgor',
        id: 1016,
        cost: 150,
        playerStats: [5, 5, 4, 0, 9],
        skills: [71, 30, 17, 55, 60, 88],
        primary: ['S'],
        secondary: ['G', 'A', 'M'],
    },
    {
        position: 'Chaos Dwarf Linemen',
        id: 1017,
        cost: 60,
        playerStats: [4, 3, 4, 5, 10],
        skills: [60, 13],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Chaos Dwarf Mutants',
        id: 1018,
        cost: 60,
        playerStats: [4, 3, 4, 5, 10],
        skills: [60, 13],
        primary: ['G', 'M', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Chaos Dwarf Thrower',
        id: 1019,
        cost: 70,
        playerStats: [5, 3, 3, 3, 9],
        skills: [60, 22, 46],
        primary: ['G', 'P'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Chaos Dwarf Kicker',
        id: 1020,
        cost: 80,
        playerStats: [4, 3, 4, 4, 10],
        skills: [60, 13, 18, 15],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Chaos Dwarf Blitzer',
        id: 1021,
        cost: 100,
        playerStats: [6, 3, 3, 5, 10],
        skills: [60, 13, 1],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Peasant',
        id: 1022,
        cost: 30,
        playerStats: [6, 3, 4, 5, 8],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Squires',
        id: 1023,
        cost: 70,
        playerStats: [6, 3, 3, 3, 9],
        skills: [45, 22],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Realm Knights (Blockers)',
        id: 1024,
        cost: 90,
        playerStats: [6, 3, 3, 5, 10],
        skills: [14, 58],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Questing Knights (Blitzer)',
        id: 1025,
        cost: 110,
        playerStats: [7, 3, 3, 4, 9],
        skills: [13, 1, 14],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Linemen',
        id: 1026,
        cost: 50,
        playerStats: [6, 3, 3, 4, 8],
        skills: [60],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Runner',
        id: 1027,
        cost: 85,
        playerStats: [7, 3, 3, 3, 8],
        skills: [51, 22, 60],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Rogue',
        id: 1028,
        cost: 90,
        playerStats: [7, 3, 3, 5, 8],
        skills: [80, 20, 4],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Brawler',
        id: 1029,
        cost: 85,
        playerStats: [7, 3, 3, 5, 9],
        skills: [50, 60],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Ogre',
        id: 1030,
        cost: 140,
        playerStats: [5, 5, 4, 5, 10],
        skills: [71, 66, 55, 60, 86],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Slaves to Darkness',
        id: 1031,
        cost: 60,
        playerStats: [6, 3, 2, 4, 8],
        skills: [],
        primary: ['G', 'A', 'M'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Slaangors',
        id: 1032,
        cost: 100,
        playerStats: [7, 3, 2, 3, 8],
        skills: [30, 36],
        primary: ['G', 'A', 'M'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Slaanesh Warriors',
        id: 1033,
        cost: 110,
        playerStats: [6, 4, 3, 0, 9],
        skills: [26, 36],
        primary: ['G', 'A', 'M'],
        secondary: ['S'],
    },
    {
        position: 'Familiars',
        id: 1034,
        cost: 30,
        playerStats: [6, 1, 3, 5, 7],
        skills: [81, 85, 78, 4, 29],
        primary: ['A', 'M'],
        secondary: ['G'],
    },
    {
        position: 'Tzaangors',
        id: 1035,
        cost: 80,
        playerStats: [6, 3, 3, 3, 9],
        skills: [30, 28, 25],
        primary: ['G', 'S', 'P', 'M'],
        secondary: ['A'],
    },
    {
        position: 'Tzeentch Warriors',
        id: 1036,
        cost: 120,
        playerStats: [5, 4, 3, 4, 10],
        skills: [69, 28],
        primary: ['G', 'S', 'M'],
        secondary: ['A', 'P'],
    },
    {
        position: 'The Changeling',
        id: 1037,
        cost: 130,
        playerStats: [0, 0, 0, 0, 0],
        skills: [19, 0],
        primary: ['S', 'M'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Khorne Cultists',
        id: 1038,
        cost: 50,
        playerStats: [6, 3, 3, 4, 9],
        skills: [],
        primary: ['G', 'M'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Bloodletters',
        id: 1039,
        cost: 100,
        playerStats: [6, 4, 3, 0, 9],
        skills: [61, 17, 77, 26, 72],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Bloodthirster',
        id: 1040,
        cost: 200,
        playerStats: [5, 7, 3, 0, 10],
        skills: [710, 61, 96, 77, 60, 551, 17, 72],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Nurglings',
        id: 1041,
        cost: 20,
        playerStats: [5, 1, 4, 0, 7],
        skills: [78, 85, 81, 73, 29, 4, 82],
        primary: ['A'],
        secondary: ['G'],
    },
    {
        position: 'Plaguebearers',
        id: 1042,
        cost: 120,
        playerStats: [5, 4, 4, 5, 10],
        skills: [60, 77, 29, 27, 32, 73],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Great Unclean One',
        id: 1043,
        cost: 200,
        playerStats: [3, 6, 6, 6, 11],
        skills: [710, 66, 77, 60, 27, 29, 55, 73, 58, 32, 86],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Cultists',
        id: 1044,
        cost: 50,
        playerStats: [6, 3, 3, 4, 9],
        skills: [],
        primary: ['G', 'M'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Daemonette',
        id: 1045,
        cost: 120,
        playerStats: [7, 3, 2, 0, 8],
        skills: [26, 69, 77],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Keeper of Secrets',
        id: 1046,
        cost: 200,
        playerStats: [7, 5, 2, 0, 9],
        skills: [710, 88, 77, 28, 26, 36],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Blue Horror',
        id: 1047,
        cost: 40,
        playerStats: [6, 2, 3, 4, 8],
        skills: [81, 78, 4, 25],
        primary: ['A', 'M'],
        secondary: ['G', 'S', 'P'],
    },
    {
        position: 'Pink Horrors',
        id: 1048,
        cost: 115,
        playerStats: [6, 4, 3, 3, 9],
        skills: [28, 70, 77],
        primary: ['G', 'S', 'M'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Flamers',
        id: 1049,
        cost: 70,
        playerStats: [7, 3, 2, 3, 9],
        skills: [79, 65, 72, 77],
        primary: ['A'],
        secondary: ['G', 'S', 'P'],
    },
    {
        position: 'Lord of Change',
        id: 1050,
        cost: 200,
        playerStats: [7, 5, 3, 5, 10],
        skills: [710, 19, 88, 77, 55, 7, 36, 29],
        primary: ['S', 'M'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Drone',
        id: 1051,
        cost: 70,
        playerStats: [6, 3, 3, 5, 8],
        skills: [60, 35, 25, 77],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Soul Reavers',
        id: 1052,
        cost: 95,
        playerStats: [6, 3, 3, 0, 9],
        skills: [77, 26, 72, 60, 29],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Harvester of Souls',
        id: 1053,
        cost: 180,
        playerStats: [6, 5, 5, 6, 10],
        skills: [710, 60, 30, 33, 55, 29, 66, 77],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Ungor',
        id: 1054,
        cost: 50,
        playerStats: [7, 2, 3, 3, 8],
        skills: [4],
        primary: ['G', 'A'],
        secondary: ['S', 'P', 'M'],
    },
    {
        position: 'Centigors',
        id: 1055,
        cost: 90,
        playerStats: [6, 4, 4, 5, 10],
        skills: [30, 11, 12, 66, 93],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Bullgor',
        id: 1056,
        cost: 150,
        playerStats: [5, 5, 4, 0, 9],
        skills: [30, 17, 55, 88, 711, 60],
        primary: ['S'],
        secondary: ['G', 'A', 'M'],
    },
    {
        position: 'Warriors of Ulric',
        id: 1057,
        cost: 50,
        playerStats: [6, 3, 3, 4, 9],
        skills: [],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Wolf Kin',
        id: 1058,
        cost: 100,
        playerStats: [6, 3, 3, 5, 9],
        skills: [54, 14, 17],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Warrior Priest of Ulric',
        id: 1059,
        cost: 80,
        playerStats: [6, 3, 3, 5, 9],
        skills: [54, 13],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Teutogen Guard',
        id: 1060,
        cost: 110,
        playerStats: [5, 4, 4, 5, 10],
        skills: [54, 19],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Black Ark Corsairs',
        id: 1061,
        cost: 70,
        playerStats: [7, 3, 2, 4, 8],
        skills: [],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Doomreavers',
        id: 1062,
        cost: 80,
        playerStats: [7, 3, 2, 2, 8],
        skills: [46],
        primary: ['G', 'A', 'P'],
        secondary: ['S'],
    },
    {
        position: 'Dreadblades',
        id: 1063,
        cost: 90,
        playerStats: [7, 3, 2, 3, 8],
        skills: [54, 44],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Kraken Helms',
        id: 1064,
        cost: 100,
        playerStats: [6, 3, 2, 5, 9],
        skills: [27, 29, 34],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Neophytes',
        id: 1065,
        cost: 60,
        playerStats: [6, 3, 2, 5, 8],
        skills: [],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Assassins',
        id: 1066,
        cost: 85,
        playerStats: [7, 3, 2, 5, 8],
        skills: [20, 80],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Shadow Blades',
        id: 1067,
        cost: 110,
        playerStats: [7, 3, 2, 4, 9],
        skills: [4, 20, 80],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Executioner',
        id: 1068,
        cost: 70,
        playerStats: [6, 3, 2, 0, 9],
        skills: [79, 67],
        primary: ['G', 'A', 'S'],
        secondary: [],
    },
    {
        position: 'Dryad',
        id: 1069,
        cost: 50,
        playerStats: [5, 3, 3, 4, 10],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Dryad Birch Form',
        id: 1070,
        cost: 70,
        playerStats: [7, 3, 3, 4, 8],
        skills: [17],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Dryad Oak Form',
        id: 1071,
        cost: 90,
        playerStats: [4, 4, 6, 6, 11],
        skills: [58],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Dryad Willow Form',
        id: 1072,
        cost: 110,
        playerStats: [5, 4, 4, 5, 9],
        skills: [33, 34],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Linemen',
        id: 1073,
        cost: 60,
        playerStats: [4, 3, 4, 5, 10],
        skills: [60, 13],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Flinthand Runners',
        id: 1074,
        cost: 105,
        playerStats: [6, 3, 3, 4, 9],
        skills: [60, 45, 41, 22],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Bronzefist Runners',
        id: 1075,
        cost: 100,
        playerStats: [6, 3, 3, 3, 9],
        skills: [60, 22, 40],
        primary: ['G', 'P'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Ironfinger Runners',
        id: 1076,
        cost: 105,
        playerStats: [6, 3, 3, 4, 9],
        skills: [60, 1, 54, 22],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Engineers',
        id: 1077,
        cost: 60,
        playerStats: [4, 3, 4, 5, 10],
        skills: [60, 13],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Kickers',
        id: 1078,
        cost: 80,
        playerStats: [4, 3, 4, 5, 10],
        skills: [60, 13, 18, 15],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Runners',
        id: 1079,
        cost: 85,
        playerStats: [6, 3, 3, 4, 9],
        skills: [60, 22],
        primary: ['G', 'P'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Ballzooka',
        id: 1080,
        cost: 80,
        playerStats: [5, 3, 3, 3, 9],
        skills: [60, 38, 42],
        primary: ['G', 'P'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Bombardier',
        id: 1081,
        cost: 60,
        playerStats: [4, 3, 4, 4, 10],
        skills: [79, 65, 60],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Master Engineer',
        id: 1082,
        cost: 80,
        playerStats: [5, 3, 4, 0, 10],
        skills: [79, 67, 60],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Deathroller',
        id: 1083,
        cost: 170,
        playerStats: [4, 7, 5, 0, 11],
        skills: [710, 51, 151, 54, 72, 55, 79, 58],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Linemen',
        id: 1084,
        cost: 60,
        playerStats: [3, 3, 4, 5, 11],
        skills: [60, 13],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Blockers',
        id: 1085,
        cost: 80,
        playerStats: [4, 3, 4, 6, 11],
        skills: [60, 13, 23],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Blitzers',
        id: 1086,
        cost: 90,
        playerStats: [5, 3, 3, 5, 11],
        skills: [60, 13],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Rune Golem',
        id: 1087,
        cost: 130,
        playerStats: [3, 5, 6, 0, 11],
        skills: [71, 66, 55, 60, 31],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Norse Dwarf',
        id: 1088,
        cost: 60,
        playerStats: [5, 3, 4, 5, 9],
        skills: [60, 13, 93],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Beer Boars',
        id: 1089,
        cost: 20,
        playerStats: [5, 1, 3, 0, 6],
        skills: [4, 72, 81, 85, 94],
        primary: [],
        secondary: ['A'],
    },
    {
        position: 'Norse Dwarf Runner',
        id: 1090,
        cost: 95,
        playerStats: [6, 3, 3, 3, 9],
        skills: [60, 1, 46, 22],
        primary: ['G', 'P'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Norse Dwarf Berserker',
        id: 1091,
        cost: 90,
        playerStats: [5, 3, 3, 5, 8],
        skills: [60, 13, 6, 17],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Norse Dwarf Slayer',
        id: 1092,
        cost: 95,
        playerStats: [5, 3, 4, 0, 9],
        skills: [60, 13, 17, 14],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Ulfwerner',
        id: 1093,
        cost: 105,
        playerStats: [6, 4, 4, 0, 9],
        skills: [17],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Slayer Linemen',
        id: 1094,
        cost: 60,
        playerStats: [4, 3, 4, 5, 9],
        skills: [60, 13, 14],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Slayer Runners',
        id: 1095,
        cost: 90,
        playerStats: [6, 3, 3, 4, 9],
        skills: [60, 14, 22],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Slayers',
        id: 1096,
        cost: 95,
        playerStats: [5, 3, 4, 0, 9],
        skills: [60, 13, 17, 14],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Giant Slayers',
        id: 1097,
        cost: 110,
        playerStats: [5, 4, 4, 0, 9],
        skills: [60, 17, 14, 54],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Doom Seeker',
        id: 1098,
        cost: 80,
        playerStats: [4, 7, 3, 0, 9],
        skills: [72, 64, 79],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Earth Elemental',
        id: 1099,
        cost: 60,
        playerStats: [4, 3, 3, 4, 10],
        skills: [58],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Water Elemental',
        id: 1100,
        cost: 60,
        playerStats: [6, 3, 3, 4, 9],
        skills: [9],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Fire Elemental',
        id: 1101,
        cost: 60,
        playerStats: [6, 3, 3, 4, 9],
        skills: [17],
        primary: ['G', 'A', 'S'],
        secondary: [],
    },
    {
        position: 'Air Elemental',
        id: 1102,
        cost: 60,
        playerStats: [7, 3, 3, 3, 8],
        skills: [36, 74, 2],
        primary: ['G', 'A', 'P'],
        secondary: ['S'],
    },
    {
        position: 'Incarnate Elemental of Earth',
        id: 1103,
        cost: 170,
        playerStats: [3, 5, 5, 5, 11],
        skills: [71, 60, 58],
        primary: ['S'],
        secondary: ['G', 'A'],
        bigGuy: true,
    },
    {
        position: 'Incarnate Elemental of Water',
        id: 1104,
        cost: 170,
        playerStats: [5, 5, 4, 5, 10],
        skills: [71, 9, 16],
        primary: ['S'],
        secondary: ['G', 'A'],
        bigGuy: true,
    },
    {
        position: 'Incarnate Elemental of Fire',
        id: 1105,
        cost: 170,
        playerStats: [6, 5, 4, 5, 9],
        skills: [71, 6, 17],
        primary: ['A', 'S'],
        secondary: ['G'],
        bigGuy: true,
    },
    {
        position: 'Incarnate Elemental of Air',
        id: 1106,
        cost: 170,
        playerStats: [6, 5, 3, 2, 9],
        skills: [71, 74, 36, 46, 42],
        primary: ['A', 'S'],
        secondary: ['G', 'P'],
        bigGuy: true,
    },
    {
        position: 'Guardavía',
        id: 1107,
        cost: 50,
        playerStats: [6, 3, 3, 4, 9],
        skills: [620],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Lanzador',
        id: 1108,
        cost: 75,
        playerStats: [6, 3, 3, 2, 9],
        skills: [22, 46, 620],
        primary: ['G', 'P'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Receptor',
        id: 1109,
        cost: 80,
        playerStats: [7, 2, 2, 5, 8],
        skills: [1, 620],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Bloqueador',
        id: 1110,
        cost: 80,
        playerStats: [4, 4, 4, 5, 10],
        skills: [620],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Diestro',
        id: 1111,
        cost: 85,
        playerStats: [7, 3, 3, 4, 9],
        skills: [13, 620],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Ghosts',
        id: 1112,
        cost: 40,
        playerStats: [6, 3, 2, 0, 8],
        skills: [72, 85, 77],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Wraith',
        id: 1113,
        cost: 95,
        playerStats: [6, 3, 3, 0, 9],
        skills: [13, 29, 72, 77, 9],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Cairn Wraith',
        id: 1114,
        cost: 100,
        playerStats: [6, 3, 3, 5, 9],
        skills: [29, 9, 80, 77],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Banshee',
        id: 1115,
        cost: 110,
        playerStats: [7, 2, 2, 3, 8],
        skills: [27, 4, 29, 77, 20],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Shearl',
        id: 1116,
        cost: 30,
        playerStats: [5, 3, 4, 6, 9],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Fimm Warrior',
        id: 1117,
        cost: 60,
        playerStats: [6, 3, 4, 6, 10],
        skills: [49, 33],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Fianna Fimm',
        id: 1118,
        cost: 120,
        playerStats: [5, 4, 5, 6, 10],
        skills: [49, 27, 33, 56],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Lesser Daemon',
        id: 1119,
        cost: 75,
        playerStats: [7, 3, 3, 4, 8],
        skills: [4],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Forest Goblin',
        id: 1120,
        cost: 40,
        playerStats: [7, 2, 3, 4, 7],
        skills: [4, 81, 78],
        primary: ['A'],
        secondary: ['G', 'S', 'P'],
    },
    {
        position: 'Savage Orc',
        id: 1121,
        cost: 50,
        playerStats: [6, 3, 3, 4, 8],
        skills: [17, 60],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Spider Riders',
        id: 1122,
        cost: 120,
        playerStats: [7, 4, 3, 0, 9],
        skills: [20, 34],
        primary: ['A', 'S'],
        secondary: ['G'],
    },
    {
        position: 'Trained River Troll',
        id: 1123,
        cost: 125,
        playerStats: [4, 5, 5, 5, 10],
        skills: [711, 63, 55, 76, 77, 86, 27, 29, 75],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Forest Halfling',
        id: 1124,
        cost: 45,
        playerStats: [5, 2, 3, 4, 7],
        skills: [81, 51, 4],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Forest Halfling Thrower',
        id: 1125,
        cost: 80,
        playerStats: [5, 2, 3, 2, 7],
        skills: [81, 51, 4, 46, 22],
        primary: ['A', 'P'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Forest Halfling Catcher',
        id: 1126,
        cost: 80,
        playerStats: [6, 2, 2, 5, 7],
        skills: [81, 4, 20, 1],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Forest Halfling Blitzer',
        id: 1127,
        cost: 90,
        playerStats: [5, 2, 3, 5, 8],
        skills: [81, 51, 4, 26, 14],
        primary: ['A', 'S'],
        secondary: ['G'],
    },
    {
        position: 'Linemen',
        id: 1128,
        cost: 60,
        playerStats: [6, 3, 3, 3, 9],
        skills: [40, 44],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Full Back',
        id: 1129,
        cost: 80,
        playerStats: [6, 3, 3, 2, 9],
        skills: [40, 44, 1, 45],
        primary: ['G', 'P'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Half Backs',
        id: 1130,
        cost: 80,
        playerStats: [6, 3, 3, 2, 9],
        skills: [40, 44, 18, 42],
        primary: ['G', 'P'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Forwards',
        id: 1131,
        cost: 80,
        playerStats: [6, 3, 3, 3, 9],
        skills: [40, 44, 3, 16],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Wings',
        id: 1132,
        cost: 80,
        playerStats: [7, 3, 3, 2, 9],
        skills: [40, 44, 1],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Pixies',
        id: 1133,
        cost: 30,
        playerStats: [7, 1, 3, 6, 7],
        skills: [81, 78, 4, 85],
        primary: ['A'],
        secondary: ['G'],
    },
    {
        position: 'Giant',
        id: 1134,
        cost: 140,
        playerStats: [4, 6, 5, 5, 10],
        skills: [66, 60, 55, 51, 70],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Gnoblar Fighters',
        id: 1135,
        cost: 30,
        playerStats: [6, 2, 3, 5, 7],
        skills: [4, 78, 81],
        primary: ['A'],
        secondary: ['G', 'S', 'P'],
    },
    {
        position: 'Gnoblar Trapper',
        id: 1136,
        cost: 50,
        playerStats: [6, 2, 3, 0, 8],
        skills: [4, 78, 81, 33, 5],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Gnoblar Man Biter',
        id: 1137,
        cost: 50,
        playerStats: [6, 2, 3, 6, 8],
        skills: [4, 78, 81, 15],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Gnoblar Piggyback Rider',
        id: 1138,
        cost: 70,
        playerStats: [6, 3, 4, 6, 8],
        skills: [4, 81, 28, 35, 22],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Maneater',
        id: 1139,
        cost: 150,
        playerStats: [5, 5, 4, 5, 10],
        skills: [66, 55, 60, 86, 50],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Linemen',
        id: 1140,
        cost: 40,
        playerStats: [5, 2, 3, 4, 8],
        skills: [78, 81, 24],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Runners',
        id: 1141,
        cost: 60,
        playerStats: [7, 2, 3, 4, 7],
        skills: [22, 4, 78, 81],
        primary: ['A'],
        secondary: ['G', 'S', 'P'],
    },
    {
        position: 'Blitzers',
        id: 1142,
        cost: 70,
        playerStats: [6, 3, 3, 5, 9],
        skills: [81, 13],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Bombardier',
        id: 1143,
        cost: 40,
        playerStats: [5, 2, 3, 4, 8],
        skills: [78, 81, 65, 79, 24],
        primary: ['A'],
        secondary: ['G', 'S', 'P'],
    },
    {
        position: 'Gnomish Contraption',
        id: 1144,
        cost: 150,
        playerStats: [3, 6, 5, 0, 11],
        skills: [711, 31, 55, 58, 66, 86],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Zombie',
        id: 1145,
        cost: 40,
        playerStats: [4, 3, 4, 0, 9],
        skills: [77],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Giant Hand',
        id: 1146,
        cost: 70,
        playerStats: [6, 2, 3, 4, 7],
        skills: [25, 4, 77, 81, 22],
        primary: ['A'],
        secondary: ['G', 'P', 'S'],
    },
    {
        position: 'Patchwork-Men',
        id: 1147,
        cost: 80,
        playerStats: [5, 3, 4, 5, 9],
        skills: [13, 77, 60],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Flesh Golem',
        id: 1148,
        cost: 110,
        playerStats: [4, 4, 4, 0, 10],
        skills: [77, 58, 60],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Lineman',
        id: 1149,
        cost: 50,
        playerStats: [6, 3, 3, 4, 9],
        skills: [],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Thrower',
        id: 1150,
        cost: 90,
        playerStats: [6, 3, 3, 2, 9],
        skills: [22, 46, 47],
        primary: ['G', 'A', 'P'],
        secondary: ['S'],
    },
    {
        position: 'Catcher',
        id: 1151,
        cost: 75,
        playerStats: [8, 2, 3, 5, 8],
        skills: [1, 2, 4],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Blitzer',
        id: 1152,
        cost: 95,
        playerStats: [7, 3, 3, 4, 9],
        skills: [13, 9],
        primary: ['G', 'A', 'S'],
        secondary: ['P'],
    },
    {
        position: 'Lineman',
        id: 1153,
        cost: 30,
        playerStats: [6, 3, 4, 4, 8],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Kickers',
        id: 1154,
        cost: 65,
        playerStats: [6, 3, 4, 3, 8],
        skills: [15, 18, 42],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Blocker',
        id: 1155,
        cost: 80,
        playerStats: [5, 4, 4, 5, 9],
        skills: [55],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Blitzer',
        id: 1156,
        cost: 85,
        playerStats: [7, 3, 4, 5, 9],
        skills: [50, 22],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Ogre',
        id: 1157,
        cost: 140,
        playerStats: [5, 5, 4, 5, 10],
        skills: [71, 66, 60, 55, 86],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Hill Goblins',
        id: 1158,
        cost: 40,
        playerStats: [6, 3, 3, 4, 8],
        skills: [81],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Troglagobs',
        id: 1159,
        cost: 60,
        playerStats: [7, 2, 3, 4, 8],
        skills: [81, 78, 4, 25],
        primary: ['A'],
        secondary: ['G', 'S', 'P'],
    },
    {
        position: 'Hill Goblin Blocker',
        id: 1160,
        cost: 80,
        playerStats: [6, 3, 3, 5, 9],
        skills: [81, 13, 50],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Fire Kobold',
        id: 1161,
        cost: 45,
        playerStats: [6, 2, 3, 4, 8],
        skills: [81, 78, 4, 65, 79],
        primary: ['A'],
        secondary: ['G', 'S', 'P'],
    },
    {
        position: 'Stone Troll',
        id: 1162,
        cost: 135,
        playerStats: [4, 5, 5, 5, 11],
        skills: [63, 55, 76, 77, 31, 86, 75],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Hobgoblins',
        id: 1163,
        cost: 40,
        playerStats: [6, 3, 3, 4, 8],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Sneaky Gits',
        id: 1164,
        cost: 80,
        playerStats: [6, 3, 3, 5, 8],
        skills: [4, 10, 80],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Dirty Gits',
        id: 1165,
        cost: 50,
        playerStats: [6, 3, 3, 5, 8],
        skills: [15],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Runners',
        id: 1166,
        cost: 70,
        playerStats: [7, 3, 3, 3, 8],
        skills: [22],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Blitzers',
        id: 1167,
        cost: 70,
        playerStats: [6, 3, 3, 4, 9],
        skills: [13],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Hobgoblins',
        id: 1168,
        cost: 40,
        playerStats: [6, 3, 3, 4, 8],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Sneaky Gits',
        id: 1169,
        cost: 80,
        playerStats: [6, 3, 3, 5, 8],
        skills: [4, 10, 80],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Black Orc Blockers',
        id: 1170,
        cost: 90,
        playerStats: [4, 4, 4, 5, 10],
        skills: [620, 50, 52],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Troll',
        id: 1171,
        cost: 115,
        playerStats: [4, 5, 5, 5, 10],
        skills: [71, 63, 55, 76, 77, 86, 75],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Linemen',
        id: 1172,
        cost: 40,
        playerStats: [5, 3, 3, 4, 9],
        skills: [],
        primary: ['G', 'M'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Hung Marauders',
        id: 1173,
        cost: 70,
        playerStats: [5, 3, 3, 4, 9],
        skills: [29, 50],
        primary: ['G', 'S', 'M'],
        secondary: ['A'],
    },
    {
        position: 'Darksouls',
        id: 1174,
        cost: 90,
        playerStats: [6, 3, 3, 5, 9],
        skills: [52, 24],
        primary: ['G', 'M'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Tong',
        id: 1175,
        cost: 100,
        playerStats: [5, 4, 4, 0, 9],
        skills: [17, 29, 620],
        primary: ['G', 'M', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Linemen',
        id: 1176,
        cost: 40,
        playerStats: [6, 3, 3, 4, 8],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Kalites',
        id: 1177,
        cost: 80,
        playerStats: [7, 3, 3, 3, 8],
        skills: [28, 41],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Rakshaka',
        id: 1178,
        cost: 115,
        playerStats: [6, 4, 3, 5, 9],
        skills: [50, 26],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Trained Basilisk',
        id: 1179,
        cost: 140,
        playerStats: [5, 5, 5, 0, 10],
        skills: [711, 76, 26, 69, 33],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Ganasa',
        id: 1180,
        cost: 140,
        playerStats: [5, 5, 5, 0, 10],
        skills: [71, 66, 30, 33, 55, 60],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Slaves',
        id: 1181,
        cost: 50,
        playerStats: [6, 3, 3, 5, 9],
        skills: [],
        primary: ['G', 'M'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Kurgan Marauders',
        id: 1182,
        cost: 70,
        playerStats: [6, 3, 3, 4, 9],
        skills: [13],
        primary: ['G', 'S', 'M'],
        secondary: ['A'],
    },
    {
        position: 'Ravagers',
        id: 1183,
        cost: 100,
        playerStats: [6, 3, 3, 4, 9],
        skills: [13, 6, 60],
        primary: ['G', 'A', 'M'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Brutes',
        id: 1184,
        cost: 100,
        playerStats: [5, 4, 3, 5, 9],
        skills: [60],
        primary: ['G', 'S', 'M'],
        secondary: ['A'],
    },
    {
        position: 'Dust Goblins',
        id: 1185,
        cost: 30,
        playerStats: [5, 2, 4, 6, 7],
        skills: [77, 78, 81, 4],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Morbid',
        id: 1186,
        cost: 70,
        playerStats: [6, 2, 3, 5, 7],
        skills: [77, 81, 4, 22],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Bahgar Bone Giant',
        id: 1187,
        cost: 140,
        playerStats: [3, 6, 5, 6, 9],
        skills: [76, 77, 86, 60, 55, 51],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Tomb Scorpion',
        id: 1188,
        cost: 120,
        playerStats: [4, 5, 5, 0, 10],
        skills: [77, 66, 80, 26],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Ushabti',
        id: 1189,
        cost: 120,
        playerStats: [5, 5, 5, 0, 11],
        skills: [84, 55, 60, 77],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Skeleton',
        id: 1190,
        cost: 50,
        playerStats: [5, 3, 4, 6, 9],
        skills: [77, 60],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Throw-Ra',
        id: 1191,
        cost: 80,
        playerStats: [6, 3, 4, 3, 9],
        skills: [46, 77, 22, 60],
        primary: ['G', 'P'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Block-Ra',
        id: 1192,
        cost: 90,
        playerStats: [5, 3, 4, 6, 10],
        skills: [13, 77, 60],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Ushabti',
        id: 1193,
        cost: 120,
        playerStats: [5, 5, 5, 0, 11],
        skills: [84, 55, 60, 77],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Skeletons',
        id: 1194,
        cost: 40,
        playerStats: [5, 3, 4, 6, 8],
        skills: [77, 60],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Sepulchral Stalkers',
        id: 1195,
        cost: 110,
        playerStats: [6, 3, 3, 6, 9],
        skills: [77, 60, 33, 69],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Necrotects',
        id: 1196,
        cost: 50,
        playerStats: [5, 3, 4, 0, 8],
        skills: [67, 77, 79, 60],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Bomber',
        id: 1197,
        cost: 50,
        playerStats: [5, 3, 4, 4, 8],
        skills: [65, 77, 79, 44, 60],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Bone Giant',
        id: 1198,
        cost: 140,
        playerStats: [3, 6, 5, 6, 9],
        skills: [711, 76, 77, 60, 55, 51],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Skeletons',
        id: 1199,
        cost: 40,
        playerStats: [5, 3, 4, 6, 8],
        skills: [77, 60],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Blitz-Ra',
        id: 1200,
        cost: 90,
        playerStats: [6, 3, 4, 6, 9],
        skills: [77, 13, 60],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Jackal Runner',
        id: 1201,
        cost: 90,
        playerStats: [7, 3, 4, 4, 8],
        skills: [77, 4, 23, 60],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Golden Host',
        id: 1202,
        cost: 110,
        playerStats: [5, 4, 4, 6, 10],
        skills: [77, 60],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Bedouin',
        id: 1203,
        cost: 40,
        playerStats: [6, 3, 3, 4, 8],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Skeletons',
        id: 1204,
        cost: 40,
        playerStats: [5, 3, 4, 6, 8],
        skills: [77, 60],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Dervishes',
        id: 1205,
        cost: 95,
        playerStats: [7, 3, 3, 5, 9],
        skills: [17, 9],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Tomb Guardian',
        id: 1206,
        cost: 100,
        playerStats: [4, 5, 5, 0, 10],
        skills: [77],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Skeletons',
        id: 1207,
        cost: 40,
        playerStats: [5, 3, 4, 6, 8],
        skills: [77, 60],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Saurus Throw-Ra',
        id: 1208,
        cost: 120,
        playerStats: [6, 4, 5, 3, 9],
        skills: [77, 22, 46, 60],
        primary: ['G', 'S', 'P'],
        secondary: ['A'],
    },
    {
        position: 'Saurus Skeleton',
        id: 1209,
        cost: 100,
        playerStats: [5, 4, 5, 6, 9],
        skills: [77, 60],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Kroq-Ra',
        id: 1210,
        cost: 140,
        playerStats: [5, 5, 5, 0, 9],
        skills: [71, 66, 60, 77, 33, 55],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Skeleton Slaves',
        id: 1211,
        cost: 50,
        playerStats: [5, 3, 4, 6, 8],
        skills: [77, 60, 6],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Slave Throw-Ras',
        id: 1212,
        cost: 80,
        playerStats: [6, 3, 4, 3, 8],
        skills: [77, 22, 46, 6, 60],
        primary: ['G', 'P'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Catch-Ras',
        id: 1213,
        cost: 90,
        playerStats: [7, 2, 3, 6, 8],
        skills: [77, 4, 1, 44, 60],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Skeleton Pirates',
        id: 1214,
        cost: 80,
        playerStats: [5, 3, 4, 0, 8],
        skills: [77, 60, 80, 6],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Tomb Guardian Ancients',
        id: 1215,
        cost: 130,
        playerStats: [3, 5, 5, 0, 10],
        skills: [77, 55, 6],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Drop Bears',
        id: 1216,
        cost: 60,
        playerStats: [5, 2, 3, 5, 8],
        skills: [81, 78, 4, 26, 14],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Kangors',
        id: 1217,
        cost: 80,
        playerStats: [6, 3, 3, 4, 9],
        skills: [74, 36, 33],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Yowie',
        id: 1218,
        cost: 140,
        playerStats: [4, 6, 4, 5, 10],
        skills: [66, 60, 55, 51, 86],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Bray',
        id: 1219,
        cost: 30,
        playerStats: [6, 2, 3, 5, 7],
        skills: [4, 81],
        primary: ['A'],
        secondary: ['M', 'G', 'S'],
    },
    {
        position: 'Bullgors',
        id: 1220,
        cost: 150,
        playerStats: [5, 5, 4, 0, 9],
        skills: [88, 60, 17, 55, 30],
        primary: ['S'],
        secondary: ['M', 'A', 'G'],
    },
    {
        position: 'Doombull',
        id: 1221,
        cost: 160,
        playerStats: [5, 5, 4, 6, 10],
        skills: [61, 60, 17, 55, 30],
        primary: ['S', 'M'],
        secondary: ['A', 'G'],
    },
    {
        position: 'Linemen',
        id: 1222,
        cost: 50,
        playerStats: [6, 3, 3, 4, 8],
        skills: [16],
        primary: ['G'],
        secondary: ['A', 'P', 'S'],
    },
    {
        position: 'Eagle Runners',
        id: 1223,
        cost: 90,
        playerStats: [7, 3, 3, 3, 8],
        skills: [9, 22],
        primary: ['G', 'A'],
        secondary: ['P', 'S'],
    },
    {
        position: 'Vanguard Blitzers',
        id: 1224,
        cost: 90,
        playerStats: [6, 3, 3, 3, 9],
        skills: [6, 24],
        primary: ['A', 'G', 'S'],
        secondary: ['P'],
    },
    {
        position: 'Templar Blockers',
        id: 1225,
        cost: 100,
        playerStats: [6, 3, 3, 5, 10],
        skills: [52, 58],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Cresters',
        id: 1226,
        cost: 60,
        playerStats: [7, 2, 3, 4, 8],
        skills: [81, 78, 4, 25],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Ignimbrite',
        id: 1227,
        cost: 50,
        playerStats: [4, 2, 4, 4, 10],
        skills: [14, 58, 77, 6],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Giant Crab',
        id: 1228,
        cost: 140,
        playerStats: [4, 5, 5, 6, 10],
        skills: [66, 26, 9, 86, 63],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Night Goblins',
        id: 1229,
        cost: 40,
        playerStats: [6, 2, 3, 4, 8],
        skills: [4, 81, 78],
        primary: ['A'],
        secondary: ['G', 'S', 'P'],
    },
    {
        position: 'Netters',
        id: 1230,
        cost: 50,
        playerStats: [6, 2, 3, 0, 8],
        skills: [4, 81, 78, 5, 33],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Madcap Mushroom Addict*',
        id: 1231,
        cost: 60,
        playerStats: [6, 2, 3, 5, 8],
        skills: [4, 81, 78, 55, 14],
        primary: ['A', 'S'],
        secondary: ['G'],
    },
    {
        position: 'Squig Hopper',
        id: 1232,
        cost: 100,
        playerStats: [6, 4, 3, 0, 9],
        skills: [74, 36, 61, 26],
        primary: ['A', 'S'],
        secondary: ['G'],
    },
    {
        position: 'Fanatic',
        id: 1233,
        cost: 70,
        playerStats: [3, 7, 3, 0, 8],
        skills: [64, 79, 72],
        primary: ['S'],
        secondary: ['A', 'G'],
    },
    {
        position: 'Trained Stone Troll',
        id: 1234,
        cost: 135,
        playerStats: [4, 5, 5, 5, 11],
        skills: [711, 76, 86, 63, 55, 77, 31, 75],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Halflings',
        id: 1235,
        cost: 30,
        playerStats: [5, 2, 3, 4, 7],
        skills: [81, 78, 4],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Komusubi Halfling',
        id: 1236,
        cost: 50,
        playerStats: [5, 2, 3, 5, 8],
        skills: [81, 4, 16, 86],
        primary: ['A', 'G'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Ninja Halfling',
        id: 1237,
        cost: 60,
        playerStats: [6, 2, 2, 4, 7],
        skills: [4, 78, 81],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Kamikaze Halfling',
        id: 1238,
        cost: 40,
        playerStats: [5, 2, 3, 6, 7],
        skills: [4, 78, 81, 83],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Foo Statue',
        id: 1239,
        cost: 130,
        playerStats: [3, 5, 5, 0, 11],
        skills: [84, 55, 58, 60, 31, 12],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Ashigaru',
        id: 1240,
        cost: 50,
        playerStats: [6, 3, 3, 4, 9],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Samurai',
        id: 1241,
        cost: 85,
        playerStats: [7, 3, 3, 4, 9],
        skills: [13],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Warrior Monk',
        id: 1242,
        cost: 70,
        playerStats: [7, 3, 3, 0, 8],
        skills: [26],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Ninja',
        id: 1243,
        cost: 90,
        playerStats: [8, 2, 2, 4, 8],
        skills: [4, 7],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Turtlemen',
        id: 1244,
        cost: 50,
        playerStats: [4, 3, 4, 5, 10],
        skills: [31],
        primary: ['G', 'M'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Chaos Samurai',
        id: 1245,
        cost: 85,
        playerStats: [7, 3, 3, 4, 9],
        skills: [13],
        primary: ['G', 'S', 'M'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Chaos Sumo',
        id: 1246,
        cost: 100,
        playerStats: [4, 4, 4, 5, 9],
        skills: [58, 52],
        primary: ['G', 'S', 'M'],
        secondary: ['A'],
    },
    {
        position: 'Oni',
        id: 1247,
        cost: 180,
        playerStats: [5, 5, 5, 0, 10],
        skills: [710, 61, 26, 30, 17, 54, 55, 77],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Linemen',
        id: 1248,
        cost: 50,
        playerStats: [6, 3, 3, 4, 9],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Catchers',
        id: 1249,
        cost: 75,
        playerStats: [8, 2, 3, 5, 8],
        skills: [1, 2, 4],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Blunderbuss',
        id: 1250,
        cost: 80,
        playerStats: [6, 3, 3, 3, 9],
        skills: [22, 38, 42],
        primary: ['G', 'P'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Pigeon Bombers',
        id: 1251,
        cost: 60,
        playerStats: [6, 3, 5, 3, 9],
        skills: [65, 42, 39, 79],
        primary: ['G', 'P'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Steam Tank',
        id: 1252,
        cost: 180,
        playerStats: [4, 7, 5, 4, 11],
        skills: [710, 51, 17, 54, 72, 55, 79, 151, 65],
        primary: ['S'],
        secondary: ['A', 'G'],
    },
    {
        position: 'Gnoblar Linemen',
        id: 1253,
        cost: 15,
        playerStats: [5, 1, 3, 5, 6],
        skills: [4, 78, 9, 81],
        primary: ['A'],
        secondary: ['G'],
    },
    {
        position: 'Ballbelcher',
        id: 1254,
        cost: 150,
        playerStats: [5, 5, 4, 5, 10],
        skills: [66, 55, 60, 86, 59, 38, 42],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Fire Belly',
        id: 1255,
        cost: 120,
        playerStats: [5, 5, 4, 5, 10],
        skills: [66, 55, 60, 86, 65, 79],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Yheti',
        id: 1256,
        cost: 140,
        playerStats: [5, 5, 5, 0, 9],
        skills: [88, 26, 17, 27],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Gorger',
        id: 1257,
        cost: 150,
        playerStats: [6, 5, 5, 0, 10],
        skills: [61, 55, 60, 17, 0],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Ogre',
        id: 1258,
        cost: 140,
        playerStats: [5, 5, 4, 5, 10],
        skills: [66, 55, 60, 86],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Pirates',
        id: 1259,
        cost: 40,
        playerStats: [6, 3, 3, 4, 8],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Long Drongs Slayer',
        id: 1260,
        cost: 80,
        playerStats: [5, 3, 3, 5, 9],
        skills: [21, 60, 14, 62],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Black Ark Corsair',
        id: 1261,
        cost: 70,
        playerStats: [7, 3, 2, 4, 8],
        skills: [620],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Ogres',
        id: 1262,
        cost: 140,
        playerStats: [5, 5, 4, 5, 10],
        skills: [66, 71, 55, 60, 86],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Captain',
        id: 1263,
        cost: 100,
        playerStats: [6, 4, 3, 3, 9],
        skills: [43],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Savage Orc Lineman',
        id: 1264,
        cost: 50,
        playerStats: [6, 3, 3, 4, 8],
        skills: [17, 60],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Savage Blocker',
        id: 1265,
        cost: 80,
        playerStats: [5, 4, 4, 5, 8],
        skills: [17, 60],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Savage Blitzer',
        id: 1266,
        cost: 90,
        playerStats: [7, 3, 3, 5, 8],
        skills: [13, 17, 60],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Troglodyte',
        id: 1267,
        cost: 140,
        playerStats: [5, 5, 5, 0, 10],
        skills: [71, 66, 60, 55, 33, 27],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'River Troll',
        id: 1268,
        cost: 125,
        playerStats: [4, 5, 5, 5, 10],
        skills: [71, 63, 55, 76, 77, 86, 27, 29, 75],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Linemen',
        id: 1269,
        cost: 70,
        playerStats: [5, 3, 2, 4, 10],
        skills: [],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Thrower',
        id: 1270,
        cost: 80,
        playerStats: [5, 3, 2, 2, 10],
        skills: [46],
        primary: ['G', 'A', 'P'],
        secondary: ['S'],
    },
    {
        position: 'Catchers',
        id: 1271,
        cost: 90,
        playerStats: [6, 3, 2, 5, 9],
        skills: [1, 11],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Blockers',
        id: 1272,
        cost: 90,
        playerStats: [5, 3, 2, 4, 10],
        skills: [13, 52],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Clan Rat',
        id: 1273,
        cost: 50,
        playerStats: [7, 3, 3, 4, 8],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S', 'M'],
    },
    {
        position: 'Night Runners',
        id: 1274,
        cost: 60,
        playerStats: [8, 2, 3, 4, 8],
        skills: [4],
        primary: ['G', 'A'],
        secondary: ['S', 'M'],
    },
    {
        position: 'Gutter Runners',
        id: 1275,
        cost: 80,
        playerStats: [9, 2, 2, 4, 8],
        skills: [4],
        primary: ['G', 'A'],
        secondary: ['S', 'P', 'M'],
    },
    {
        position: 'Assassins',
        id: 1276,
        cost: 110,
        playerStats: [8, 3, 2, 3, 8],
        skills: [20, 80],
        primary: ['G', 'A'],
        secondary: ['S', 'P', 'M'],
    },
    {
        position: 'Bonefodder',
        id: 1277,
        cost: 40,
        playerStats: [7, 2, 3, 5, 7],
        skills: [4, 81, 60, 620],
        primary: ['A'],
        secondary: ['G', 'S', 'M'],
    },
    {
        position: 'Bonehides',
        id: 1278,
        cost: 100,
        playerStats: [7, 3, 3, 5, 9],
        skills: [13, 80, 60, 62, 0],
        primary: ['G', 'S'],
        secondary: ['A', 'P', 'M'],
    },
    {
        position: 'Warp Runners',
        id: 1279,
        cost: 160,
        playerStats: [6, 5, 4, 0, 9],
        skills: [71, 61, 55, 17, 33, 75, 60, 620],
        primary: ['S'],
        secondary: ['G', 'A', 'M'],
    },
    {
        position: 'Clan Rat',
        id: 1280,
        cost: 50,
        playerStats: [7, 3, 3, 4, 8],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S', 'M'],
    },
    {
        position: 'Storm Vermin',
        id: 1281,
        cost: 90,
        playerStats: [7, 3, 3, 5, 9],
        skills: [13],
        primary: ['G', 'S'],
        secondary: ['A', 'M'],
    },
    {
        position: 'Red Guard',
        id: 1282,
        cost: 110,
        playerStats: [7, 3, 3, 5, 10],
        skills: [13, 19],
        primary: ['G', 'S'],
        secondary: ['A', 'M'],
    },
    {
        position: 'Skaven Slaves',
        id: 1283,
        cost: 40,
        playerStats: [7, 2, 3, 5, 7],
        skills: [4, 81, 0],
        primary: ['A', 'M'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Throtlings',
        id: 1284,
        cost: 20,
        playerStats: [6, 1, 3, 5, 6],
        skills: [4, 81, 78, 9, 82, 85],
        primary: ['A', 'M'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Rat Ogres',
        id: 1285,
        cost: 150,
        playerStats: [6, 5, 4, 0, 9],
        skills: [61, 55, 17, 33],
        primary: ['S', 'M'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Armoured Rat Ogres',
        id: 1286,
        cost: 155,
        playerStats: [6, 5, 4, 0, 10],
        skills: [88, 55, 17, 33],
        primary: ['S', 'M'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Plague Monk',
        id: 1287,
        cost: 55,
        playerStats: [7, 3, 3, 5, 8],
        skills: [27],
        primary: ['G'],
        secondary: ['A', 'S', 'M'],
    },
    {
        position: 'Plague Carrier',
        id: 1288,
        cost: 70,
        playerStats: [7, 3, 3, 4, 8],
        skills: [29, 27, 22],
        primary: ['G'],
        secondary: ['A', 'S', 'P', 'M'],
    },
    {
        position: 'Plague Priest',
        id: 1289,
        cost: 110,
        playerStats: [7, 3, 3, 5, 9],
        skills: [29, 27, 17, 58],
        primary: ['G', 'S'],
        secondary: ['A', 'M'],
    },
    {
        position: 'Plague Censer Bearer',
        id: 1290,
        cost: 120,
        playerStats: [3, 7, 3, 0, 8],
        skills: [64, 72, 27],
        primary: ['S', 'M'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Clan Rats',
        id: 1291,
        cost: 50,
        playerStats: [7, 3, 3, 4, 8],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S', 'P', 'M'],
    },
    {
        position: 'Mecha Vermin',
        id: 1292,
        cost: 80,
        playerStats: [5, 4, 5, 6, 10],
        skills: [31],
        primary: ['G', 'S'],
        secondary: ['A', 'M'],
    },
    {
        position: 'Jezzail',
        id: 1293,
        cost: 80,
        playerStats: [7, 3, 3, 3, 8],
        skills: [22, 38, 42],
        primary: ['G', 'P'],
        secondary: ['A', 'S', 'M'],
    },
    {
        position: 'Poison Wind Globadiers',
        id: 1294,
        cost: 50,
        playerStats: [6, 3, 3, 4, 9],
        skills: [65, 79],
        primary: ['G'],
        secondary: ['A', 'S', 'P', 'M'],
    },
    {
        position: 'Warp Grinder',
        id: 1295,
        cost: 50,
        playerStats: [7, 3, 3, 0, 8],
        skills: [67, 79],
        primary: ['G'],
        secondary: ['A', 'S', 'M'],
    },
    {
        position: 'Doom Flayers',
        id: 1296,
        cost: 170,
        playerStats: [5, 7, 5, 0, 10],
        skills: [710, 51, 17, 54, 72, 55, 79, 151],
        primary: ['S'],
        secondary: ['G', 'A', 'M'],
    },
    {
        position: 'Sisters',
        id: 1297,
        cost: 50,
        playerStats: [5, 3, 3, 4, 10],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Purifiers',
        id: 1298,
        cost: 70,
        playerStats: [6, 3, 3, 5, 9],
        skills: [80],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Augurs',
        id: 1299,
        cost: 90,
        playerStats: [7, 3, 3, 3, 8],
        skills: [22, 19, 44],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Sister Superior',
        id: 1300,
        cost: 80,
        playerStats: [5, 3, 3, 4, 10],
        skills: [13, 5],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Matriarch',
        id: 1301,
        cost: 120,
        playerStats: [5, 4, 4, 5, 10],
        skills: [14, 55],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Skink',
        id: 1302,
        cost: 60,
        playerStats: [8, 2, 3, 4, 8],
        skills: [81, 4],
        primary: ['A'],
        secondary: ['G', 'S', 'P'],
    },
    {
        position: 'Chameleon Skink',
        id: 1303,
        cost: 70,
        playerStats: [7, 2, 3, 3, 8],
        skills: [81, 4, 20, 45],
        primary: ['A'],
        secondary: ['G', 'S', 'P'],
    },
    {
        position: 'Red Crested Skink',
        id: 1304,
        cost: 80,
        playerStats: [8, 2, 3, 5, 8],
        skills: [81, 4, 14],
        primary: ['A', 'G'],
        secondary: ['S'],
    },
    {
        position: 'Kroxigor',
        id: 1305,
        cost: 140,
        playerStats: [6, 5, 5, 0, 10],
        skills: [66, 60, 55, 33],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Snakemen',
        id: 1306,
        cost: 60,
        playerStats: [6, 3, 3, 4, 9],
        skills: [33],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Runner',
        id: 1307,
        cost: 100,
        playerStats: [7, 3, 3, 3, 8],
        skills: [33, 4, 8, 9],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Mesmer',
        id: 1308,
        cost: 80,
        playerStats: [6, 3, 3, 4, 9],
        skills: [33, 69],
        primary: ['G', 'M'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Constrictors',
        id: 1309,
        cost: 100,
        playerStats: [5, 4, 4, 5, 9],
        skills: [34],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Pirate Cultists',
        id: 1310,
        cost: 40,
        playerStats: [6, 3, 3, 4, 8],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Wrecker',
        id: 1311,
        cost: 70,
        playerStats: [6, 3, 3, 3, 8],
        skills: [95, 22],
        primary: ['G', 'P'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Sons of Stromfels',
        id: 1312,
        cost: 110,
        playerStats: [4, 5, 4, 5, 10],
        skills: [26, 17, 61],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Squig Herders',
        id: 1313,
        cost: 40,
        playerStats: [6, 2, 3, 4, 8],
        skills: [4, 81, 78],
        primary: ['A'],
        secondary: ['G', 'S', 'P'],
    },
    {
        position: 'Cave Squig',
        id: 1314,
        cost: 80,
        playerStats: [6, 4, 3, 0, 9],
        skills: [74, 36, 26, 76, 72],
        primary: ['A', 'S'],
        secondary: ['G'],
    },
    {
        position: 'Squig Hopper',
        id: 1315,
        cost: 100,
        playerStats: [6, 4, 3, 0, 9],
        skills: [26, 74, 36, 61],
        primary: ['A', 'S'],
        secondary: ['G'],
    },
    {
        position: 'Giant Cave Squig',
        id: 1316,
        cost: 110,
        playerStats: [4, 5, 5, 0, 10],
        skills: [711, 26, 76, 72, 60],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Mangler Squig',
        id: 1317,
        cost: 120,
        playerStats: [3, 7, 3, 0, 9],
        skills: [64, 26, 72],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Squig Gobba',
        id: 1318,
        cost: 80,
        playerStats: [1, 5, 5, 2, 10],
        skills: [65, 79, 26, 42, 76, 72],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Tilean Lineman',
        id: 1319,
        cost: 40,
        playerStats: [6, 3, 3, 4, 8],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Spites',
        id: 1320,
        cost: 20,
        playerStats: [6, 1, 3, 5, 7],
        skills: [4, 81, 85, 78, 9],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Treemen',
        id: 1321,
        cost: 120,
        playerStats: [2, 6, 5, 5, 11],
        skills: [87, 84, 55, 60, 59, 86, 58],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Goblins',
        id: 1322,
        cost: 40,
        playerStats: [6, 2, 3, 4, 8],
        skills: [4, 81, 78],
        primary: ['A'],
        secondary: ['G', 'S', 'P'],
    },
    {
        position: 'Snotlings',
        id: 1323,
        cost: 15,
        playerStats: [5, 1, 3, 5, 6],
        skills: [4, 78, 9, 81, 82, 85],
        primary: ['A'],
        secondary: ['G'],
    },
    {
        position: 'Trolls',
        id: 1324,
        cost: 115,
        playerStats: [4, 5, 5, 5, 10],
        skills: [63, 55, 76, 77, 86, 75],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'River Troll',
        id: 1325,
        cost: 125,
        playerStats: [4, 5, 5, 5, 10],
        skills: [63, 27, 29, 55, 76, 77, 86, 75],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Stone Troll',
        id: 1326,
        cost: 135,
        playerStats: [4, 5, 5, 5, 11],
        skills: [63, 55, 76, 77, 31, 86, 75],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Zombies',
        id: 1327,
        cost: 40,
        playerStats: [4, 3, 4, 0, 9],
        skills: [77],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Skeleton Pirates',
        id: 1328,
        cost: 80,
        playerStats: [5, 3, 4, 0, 8],
        skills: [77, 60, 6, 80],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Syreen',
        id: 1329,
        cost: 110,
        playerStats: [7, 3, 3, 3, 9],
        skills: [29, 27, 9, 20],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Animated Hulk',
        id: 1330,
        cost: 130,
        playerStats: [4, 5, 5, 0, 10],
        skills: [71, 66, 77, 60, 55],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Vampire Lord',
        id: 1331,
        cost: 160,
        playerStats: [6, 5, 2, 3, 9],
        skills: [77, 69, 61],
        primary: ['G', 'A', 'S'],
        secondary: ['P'],
    },
    {
        position: 'Linewomen',
        id: 1332,
        cost: 50,
        playerStats: [6, 3, 3, 4, 8],
        skills: [13],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Thrower',
        id: 1333,
        cost: 70,
        playerStats: [6, 3, 3, 2, 8],
        skills: [13, 46],
        primary: ['G', 'P'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Catcher',
        id: 1334,
        cost: 70,
        playerStats: [6, 3, 3, 5, 8],
        skills: [13, 1],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Beserker',
        id: 1335,
        cost: 90,
        playerStats: [6, 3, 3, 5, 8],
        skills: [13, 6, 17],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Ogress',
        id: 1336,
        cost: 140,
        playerStats: [5, 5, 4, 5, 10],
        skills: [71, 55, 60, 86, 66],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Minotaur',
        id: 1337,
        cost: 150,
        playerStats: [5, 5, 4, 6, 9],
        skills: [71, 88, 60, 17, 55, 30],
        primary: ['S'],
        secondary: ['A', 'G'],
    },
    {
        position: 'Stone Troll',
        id: 1338,
        cost: 135,
        playerStats: [4, 5, 5, 5, 11],
        skills: [71, 76, 86, 63, 55, 31, 77],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Yhetee',
        id: 1339,
        cost: 140,
        playerStats: [5, 5, 4, 6, 9],
        skills: [71, 88, 26, 17, 27],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Thralls',
        id: 1340,
        cost: 40,
        playerStats: [6, 3, 3, 5, 8],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Zombies',
        id: 1341,
        cost: 40,
        playerStats: [4, 3, 4, 0, 9],
        skills: [77],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Grave Guard',
        id: 1342,
        cost: 80,
        playerStats: [5, 3, 4, 5, 10],
        skills: [77, 13],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Blood Dragon Vampires',
        id: 1343,
        cost: 110,
        playerStats: [6, 4, 3, 3, 10],
        skills: [97, 55, 54, 77, 69],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Linemen',
        id: 1344,
        cost: 50,
        playerStats: [6, 3, 3, 4, 9],
        skills: [0],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Blitzers',
        id: 1345,
        cost: 90,
        playerStats: [7, 3, 3, 4, 9],
        skills: [13, 0],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Lahmian Vampires',
        id: 1346,
        cost: 110,
        playerStats: [7, 3, 2, 3, 8],
        skills: [96, 4, 77, 69],
        primary: ['G', 'A', 'S'],
        secondary: ['P'],
    },
    {
        position: 'Skeletons',
        id: 1347,
        cost: 40,
        playerStats: [5, 3, 4, 6, 8],
        skills: [60, 77],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Wights',
        id: 1348,
        cost: 90,
        playerStats: [6, 3, 3, 5, 9],
        skills: [13, 77],
        primary: ['G', 'S'],
        secondary: ['A', 'P'],
    },
    {
        position: 'Necrarch Vampires',
        id: 1349,
        cost: 110,
        playerStats: [6, 3, 2, 4, 9],
        skills: [77, 29, 69],
        primary: ['G', 'A', 'S'],
        secondary: ['P'],
    },
    {
        position: 'Zombies',
        id: 1350,
        cost: 40,
        playerStats: [4, 3, 4, 6, 9],
        skills: [77],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Blood Boars',
        id: 1351,
        cost: 20,
        playerStats: [5, 1, 3, 0, 6],
        skills: [4, 72, 81, 85, 94, 0],
        primary: [],
        secondary: ['A'],
    },
    {
        position: 'Ghouls',
        id: 1352,
        cost: 70,
        playerStats: [7, 3, 3, 4, 8],
        skills: [4, 0],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Strigoi',
        id: 1353,
        cost: 100,
        playerStats: [6, 4, 3, 4, 9],
        skills: [96, 26, 77, 69],
        primary: ['G', 'S', 'A'],
        secondary: ['P'],
    },
    {
        position: 'Crypt Horror',
        id: 1354,
        cost: 150,
        playerStats: [5, 5, 4, 0, 11],
        skills: [97, 26, 71, 77],
        primary: ['S'],
        secondary: ['A', 'G'],
    },
    {
        position: 'Thralls',
        id: 1355,
        cost: 40,
        playerStats: [6, 3, 3, 4, 8],
        skills: [0],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Von Carstein Vampires',
        id: 1356,
        cost: 110,
        playerStats: [6, 4, 2, 2, 9],
        skills: [96, 77, 69],
        primary: ['G', 'A', 'S'],
        secondary: ['P'],
    },
    {
        position: 'Werecat',
        id: 1357,
        cost: 50,
        playerStats: [7, 2, 2, 3, 8],
        skills: [6],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Werewolves',
        id: 1358,
        cost: 125,
        playerStats: [8, 3, 3, 4, 9],
        skills: [26, 17, 77],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Werebear',
        id: 1359,
        cost: 110,
        playerStats: [4, 5, 5, 0, 9],
        skills: [76, 55, 60, 52],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Zealot',
        id: 1360,
        cost: 40,
        playerStats: [6, 3, 3, 4, 8],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'S'],
    },
    {
        position: 'Flagellants',
        id: 1361,
        cost: 50,
        playerStats: [6, 3, 4, 0, 8],
        skills: [5, 17, 60],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Warrior Priests',
        id: 1362,
        cost: 105,
        playerStats: [6, 3, 3, 4, 10],
        skills: [13, 16, 14],
        primary: ['G', 'S'],
        secondary: ['A'],
    },
    {
        position: 'Witch Hunters',
        id: 1363,
        cost: 95,
        playerStats: [7, 3, 3, 3, 9],
        skills: [13, 80],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: "Sigmar's Anvil",
        id: 1364,
        cost: 70,
        playerStats: [3, 7, 3, 0, 8],
        skills: [79, 64, 72],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Wild Hunters',
        id: 1365,
        cost: 65,
        playerStats: [6, 3, 2, 3, 8],
        skills: [17],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Shape Changer - Boar',
        id: 1366,
        cost: 80,
        playerStats: [7, 3, 2, 4, 8],
        skills: [30],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Shape Changer - Bear',
        id: 1367,
        cost: 100,
        playerStats: [6, 3, 2, 4, 9],
        skills: [26, 14],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Shape Changer - Wolf',
        id: 1368,
        cost: 90,
        playerStats: [7, 3, 2, 4, 8],
        skills: [26, 17],
        primary: ['G', 'A'],
        secondary: ['S'],
    },
    {
        position: 'Kurnocervus',
        id: 1369,
        cost: 150,
        playerStats: [5, 5, 4, 0, 9],
        skills: [711, 88, 30, 60, 55, 17],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'Sisters of the Thorn',
        id: 1370,
        cost: 75,
        playerStats: [6, 3, 2, 2, 8],
        skills: [77],
        primary: ['G', 'A', 'P'],
        secondary: ['S'],
    },
    {
        position: 'Spites',
        id: 1371,
        cost: 20,
        playerStats: [6, 1, 3, 5, 7],
        skills: [4, 81, 85, 78, 9],
        primary: ['A'],
        secondary: ['G', 'S'],
    },
    {
        position: 'Naiads',
        id: 1372,
        cost: 105,
        playerStats: [7, 3, 2, 3, 8],
        skills: [77, 9],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Great Sylph',
        id: 1373,
        cost: 160,
        playerStats: [6, 5, 4, 3, 9],
        skills: [711, 88, 77, 55, 9, 27],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Zoat Juven',
        id: 1374,
        cost: 50,
        playerStats: [6, 3, 4, 4, 9],
        skills: [12],
        primary: ['G'],
        secondary: ['A', 'S', 'P'],
    },
    {
        position: 'Zoat',
        id: 1375,
        cost: 110,
        playerStats: [5, 5, 5, 5, 9],
        skills: [50, 12],
        primary: ['S'],
        secondary: ['G', 'A'],
    },
    {
        position: 'The Forsaken - Khorne',
        id: 1376,
        cost: 60,
        playerStats: [6, 3, 3, 4, 9],
        skills: [30],
        primary: ['G', 'M'],
        secondary: ['S', 'A', 'P'],
    },
    {
        position: 'The Forsaken - Slaanesh',
        id: 1377,
        cost: 60,
        playerStats: [6, 3, 3, 4, 9],
        skills: [33],
        primary: ['G', 'M'],
        secondary: ['S', 'A', 'P'],
    },
    {
        position: 'The Forsaken - Nurgle',
        id: 1378,
        cost: 60,
        playerStats: [6, 3, 3, 4, 9],
        skills: [29, 27],
        primary: ['G', 'M'],
        secondary: ['S', 'A', 'P'],
    },
    {
        position: 'The Forsaken - Tzeentch',
        id: 1379,
        cost: 60,
        playerStats: [6, 3, 3, 4, 9],
        skills: [28, 25],
        primary: ['G', 'M'],
        secondary: ['S', 'A', 'P'],
    },
    {
        position: 'Spawn',
        id: 1380,
        cost: 60,
        playerStats: [4, 5, 3, 0, 9],
        skills: [64, 72, 26],
        primary: ['S', 'M'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Beast Of Nurgle',
        id: 1381,
        cost: 140,
        playerStats: [4, 5, 5, 0, 10],
        skills: [27, 29, 55, 0, 76, 77, 34],
        primary: ['S', 'M'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Blood Beast',
        id: 1382,
        cost: 140,
        playerStats: [5, 5, 5, 0, 9],
        skills: [0, 26, 17, 60],
        primary: ['S', 'M'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Fiend',
        id: 1383,
        cost: 140,
        playerStats: [6, 5, 4, 0, 9],
        skills: [76, 26, 72, 33, 12, 11],
        primary: ['S', 'M'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Fire Wyrm',
        id: 1384,
        cost: 140,
        playerStats: [4, 5, 5, 0, 9],
        skills: [66, 72, 65, 29, 77],
        primary: ['S', 'M'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Daemon Prince',
        id: 1385,
        cost: 180,
        playerStats: [5, 6, 4, 5, 10],
        skills: [71, 26, 66, 60, 77],
        primary: ['S'],
        secondary: ['M', 'G', 'A', 'P'],
    },
    {
        position: 'Renegades',
        id: 1386,
        cost: 50,
        playerStats: [6, 3, 3, 3, 9],
        skills: [],
        primary: ['G'],
        secondary: ['A', 'P', 'S'],
    },
    {
        position: 'Beast of Malal',
        id: 1387,
        cost: 140,
        playerStats: [6, 5, 5, 0, 9],
        skills: [71, 76, 77, 26, 72, 60, 29, 12],
        primary: ['S'],
        secondary: ['G', 'A', 'P'],
    },
    {
        position: 'Lineman',
        id: 1388,
        cost: 50,
        playerStats: [6, 3, 3, 3, 9],
        skills: [0],
        primary: ['G', 'A'],
        secondary: ['S', 'P'],
    },
    {
        position: 'Werewolves',
        id: 1389,
        cost: 125,
        playerStats: [8, 3, 3, 4, 9],
        skills: [26, 17, 77],
        primary: [],
        secondary: [],
    },
];
