name: End-to-end tests
on: [pull_request]
jobs:
    cypress-run:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Check pr
              if: ${{refs/pull/:prNumber/merge == 2}}
              run: echo "nice"
            - name: Cypress run
              uses: cypress-io/github-action@v2

              # env:
              #     CYPRESS_BASE_URL: 'https://deploy-preview-${{refs/pull/:prNumber/merge}}--bbroster.netlify.app/'
